"""add_household_invites

Revision ID: 1411f7138911
Revises: ea578ad14474
Create Date: 2026-03-01 14:21:07.503312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1411f7138911'
down_revision: Union[str, Sequence[str], None] = 'ea578ad14474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_invites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_household_invites_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_invites')),
    sa.UniqueConstraint('household_id', name=op.f('uq_household_invites_household_id')),
    sa.UniqueConstraint('token', name=op.f('uq_household_invites_token'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('household_invites')
    # ### end Alembic commands ###
