"""shopping_items_recipe_id_on_delete_set_null

Revision ID: 15488f45898b
Revises: c2f59cca1f60
Create Date: 2026-03-01 10:26:54.187029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15488f45898b'
down_revision: Union[str, Sequence[str], None] = 'c2f59cca1f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_shopping_items_recipe_id_recipes'), 'shopping_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shopping_items_recipe_id_recipes'), 'shopping_items', 'recipes', ['recipe_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_shopping_items_recipe_id_recipes'), 'shopping_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shopping_items_recipe_id_recipes'), 'shopping_items', 'recipes', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
