"""float_quantities

Revision ID: a1e52cc68033
Revises: ab422bea9156
Create Date: 2026-02-18 21:39:30.339174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e52cc68033'
down_revision: Union[str, Sequence[str], None] = 'ab422bea9156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'quantity',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using="CASE WHEN quantity ~ '^[0-9]+(\\.[0-9]+)?$' THEN quantity::float ELSE NULL END")
    op.alter_column('shopping_items', 'quantity',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using="CASE WHEN quantity ~ '^[0-9]+(\\.[0-9]+)?$' THEN quantity::float ELSE NULL END")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopping_items', 'quantity',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('ingredients', 'quantity',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
