"""add_category_to_shopping_items

Revision ID: c2f59cca1f60
Revises: a1e52cc68033
Create Date: 2026-03-01 10:24:45.343835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f59cca1f60'
down_revision: Union[str, Sequence[str], None] = 'a1e52cc68033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_items', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_items', 'category')
    # ### end Alembic commands ###
