"""add_created_by_to_recipes

Revision ID: ea578ad14474
Revises: 878971226811
Create Date: 2026-03-01 12:36:50.569165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea578ad14474'
down_revision: Union[str, Sequence[str], None] = '878971226811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('created_by_id', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_recipes_created_by_id_users'), 'recipes', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_recipes_created_by_id_users'), 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'created_by_id')
    # ### end Alembic commands ###
